// ============================================================
// CONVERSATION LIBRARY 5 — culture, specific words, deeper Nigerian flavour
// ============================================================
var LIB5 = [

// ============ NIGERIAN CULTURE (30) ============
{ p: /\b(naija|9ja|naija no dey carry last|nigerian)\b/i,
  r: ['Naija 🇳🇬 o','9ja no dey carry last','we dey o','my country'] },
{ p: /\b(africa|african|ghana|gh|kenya|uganda|south africa)\b/i,
  r: ['Africa to the world 🌍','where you from?','we dey o','🇳🇬'] },
{ p: /\b(abi|ehen na|na so)\b/i,
  r: ['na so o','ehen na','abi o','you sabi o'] },
{ p: /\b(omugwo|owanbe|aso ebi|gele|agbada|buba|kaftan)\b/i,
  r: ['party dey sweet o 🎉','which event?','aso ebi don land','🕺'] },
{ p: /\b(small chops|jollof|ofada|ewedu|egusi|pepper soup|suya|kilishi)\b/i,
  r: ['na my favourite 😋','see food!','make I come','hungry dey worry me'] },
{ p: /\b(snacks|shawarma|puff puff|akara|puffpuff|meat pie|sausage roll|chin chin)\b/i,
  r: ['😋 send am come','hungry dey o','make I come chop','e sweet o'] },

// ============ GHANAIAN FLAVOUR (15) ============
{ p: /\b(chale|chale wote|trotro|accra|kumasi|tamale|jollof war)\b/i,
  r: ['chale o','Accra to the world 🌍','we dey o','which side you dey?'] },
{ p: /\b(waakye|banku|kenkey|fufu|kontomire|red red|jollof|gobe)\b/i,
  r: ['banku sweet o 😋','chale make we chop','food dey o','hungry dey worry me'] },

// ============ SPECIFIC PHRASES (40) ============
{ p: /\b(no dey whine me|no dey do me|no dey whine|stop whining me)\b/i,
  r: ['no be whine o','I serious','chill na','you dey hear?'] },
{ p: /\b(you dey mad|you don mad|don crase|don kolo)\b/i,
  r: ['chill na 😅','wetin happen?','no insult o','abeg'] },
{ p: /\b(me I no know o|me I no gree|me I dey o)\b/i,
  r: ['ehen na','na so o','I hear you'] },
{ p: /\b(i go soon|i go soon come|i go soon reach)\b/i,
  r: ['ok na','sharp sharp','we dey wait','dey come'] },
{ p: /\b(no be today|no be today o|long time|since)\b/i,
  r: ['na so o','e don tay o','I know na','chai'] },
{ p: /\b(na only you|na only you o|only you)\b/i,
  r: ['no be only me o 😂','you sef','chill na','na you too'] },
{ p: /\b(na so so|na so so talk|na so so thing)\b/i,
  r: ['na so o','ehen na','chai','see talk'] },
{ p: /\b(see talk|see this talk|see person)\b/i,
  r: ['chai 😂','see this thing','you dey o','ewo'] },
{ p: /\b(you dey ment|you dey form|you dey pose)\b/i,
  r: ['chill o 😂','no form for me','ehen na','you too much'] },
{ p: /\b(i don die|i don dead|i don pass away)\b/i,
  r: ['😂😂 chai','ewo','see this thing','you funny o'] },
{ p: /\b(no vex na|no vex abeg|no vex now)\b/i,
  r: ['no wahala o','ehen nothing','we dey o','chill'] },
{ p: /\b(holy ghost fire|fire fire|fire)\b/i,
  r: ['🔥🔥','fire o','see fire','na fire'] },
{ p: /\b(shine your eye|shine eye|open eye)\b/i,
  r: ['eye don open o','chai','we dey watch','ehen na'] },
{ p: /\b(gbe body|gbe body e|correct guy)\b/i,
  r: ['gbe body e 💃','na so o','you too much','🔥'] },
{ p: /\b(leg work|legwork|hustle|grind)\b/i,
  r: ['hustle dey go o','grind o 💪','no be small thing','we dey push'] },
{ p: /\b(no carry last|carry last)\b/i,
  r: ['9ja no dey carry last 🇳🇬','we dey front o','no worry'] },
{ p: /\b(eye service|eye service o)\b/i,
  r: ['chill o','we no dey do that','no eye service here'] },
{ p: /\b(shine shine bobo|shine bobo)\b/i,
  r: ['shine o ✨','baddo 🔥','you too much','na so'] },
{ p: /\b(mind your business|mydb|mbb)\b/i,
  r: ['chill o','no vex','abeg','ok na'] },
{ p: /\b(chei!|chei o|chei\s*!)\s*$/i,
  r: ['chai o','na wa','ewo','see this thing'] },

// ============ DAILY LIFE EVENTS (25) ============
{ p: /\b(i don wake|i wake up|i just woke)\b/i,
  r: ['morning o ☀️','how you sleep?','morn don break o'] },
{ p: /\b(i wan sleep|i dey go sleep|going to bed)\b/i,
  r: ['night o 🌙','sleep well','later o'] },
{ p: /\b(i wan eat|i dey hungry|hungry dey worry me)\b/i,
  r: ['food dey o 😋','make I come chop','hungry na wahala'] },
{ p: /\b(i wan go work|going to work|work dey)\b/i,
  r: ['hustle o 💪','safe journey','work dey go o'] },
{ p: /\b(i wan go school|going to school)\b/i,
  r: ['school o 📚','read well','study hard'] },
{ p: /\b(i just chop|i don eat|done eating)\b/i,
  r: ['😋 enjoy','food sweet?','make I come sef'] },
{ p: /\b(i dey tired|i tire|body dey pain me)\b/i,
  r: ['same here o 😴','go rest o','take am easy','no wahala'] },
{ p: /\b(i wan relax|chilling|just dey chill)\b/i,
  r: ['same here o 😎','soft life o','enjoy'] },
{ p: /\b(i just land|i don reach)\b/i,
  r: ['welcome o 👋','safe landing','ehen'] },
{ p: /\b(i dey on my way|coming)\b/i,
  r: ['ok na','sharp sharp','dey come','we dey wait'] },

// ============ COMMON WORDS (35) ============
{ p: /\b(sharp\s*sharp)\b/i,
  r: ['sharp sharp 👍','ehen na','💯','ok o'] },
{ p: /\b(plenty\s*money)\b/i,
  r: ['money o 💸','God when? 😩','same here o','chai'] },
{ p: /\b(small\s*time)\b/i,
  r: ['ok na','we dey wait','sharp sharp','alright'] },
{ p: /\b(big\s*man)\b/i,
  r: ['na you o 🙏','respect o','you too much','👍'] },
{ p: /\b(shakara|blessing)\b/i,
  r: ['🙏','God dey o','ehen na'] },
{ p: /\b(gbedu|gbam)\b/i,
  r: ['gbam! 💯','na so o','exactly'] },
{ p: /\b(now now|right now|immediately)\b/i,
  r: ['ok na','sharp sharp','dey come','wait small'] },
{ p: /\b(e go soon happen|e go happen)\b/i,
  r: ['we go see','God dey o','e go better','amen'] },
{ p: /\b(no be me o|no be me)\b/i,
  r: ['na you o 😂','chill na','abeg'] },
{ p: /\b(anything|whatever|any how)\b/i,
  r: ['ok o','ehen','chill','we dey jare'] },
{ p: /\b(shebi|shey)\s/i,
  r: ['shey?','ehen na','abi o','na so'] },
{ p: /\b(walahi|wallahi|i swear)\b/i,
  r: ['I swear o','no be lie','na true','chill'] },
{ p: /\b(nonsense|nonsense talk|rubbish)\b/i,
  r: ['chill o','no vex','abeg','wetin happen?'] },
{ p: /\b(sharp guy|sharp girl|correct person)\b/i,
  r: ['na you o 😎','you too much','respect 🙏','👍'] },
{ p: /\b(come and eat|come chop)\b/i,
  r: ['😋 coming o','make I come','food dey o'] },
{ p: /\b(follow me|check me out|my page|my handle)\b/i,
  r: ['link?','which one?','send am come','👀'] },
{ p: /\b(link)\b/i,
  r: ['send link','which link?','wetyn dey inside?','ok o'] },

// ============ MORE GREETINGS (20) ============
{ p: /\b(hey\s*(guy|guys|bro|man|fam))\b/i,
  r: ['sup bro','yo 😎','wetin dey','how far?'] },
{ p: /\b(hi\s*(guy|guys|bro|man|fam|chief))\b/i,
  r: ['hey guy 👋','sup bro','wetin dey o'] },
{ p: /\b(greetings|greet|i greet)\b/i,
  r: ['greetings o','same to you','ehen na','👋'] },
{ p: /\b(good\s*(day|dy))\b/i,
  r: ['good day o ☀️','how you dey?','ehen same to you'] },
{ p: /\b(how\s*body)\b/i,
  r: ['body dey o','I dey, you?','we dey jare'] },

// ============ CATEGORY: RESPONSES TO PHOTOS/VIDEOS (10) ============
{ p: /\b(nice pic|nice photo|nice one|nice view)\b/i,
  r: ['🙏','thanks o','you too much','👍'] },
{ p: /\b(you fine|you beautiful|you pretty)\b/i,
  r: ['😏','abeg jare','you too much o','🙈'] },
{ p: /\b(sha|whatsapp status|status)\b/i,
  r: ['which status?','I don see am','ehen na'] },

// ============ MISC CONVERSATION (25) ============
{ p: /\b(let\'?s\s*(talk|gist|chat|vibe))\b/i,
  r: ['ok na','wetin you want talk?','I dey hear','talk to me'] },
{ p: /\b(you see am|you see?|you see)\b/i,
  r: ['yes o','I see am','ehen na','chill'] },
{ p: /\b(wetin happen|what happened)\s*$/i,
  r: ['nothing o','we dey o','wetyn you hear?','talk am'] },
{ p: /\b(i dey back|am back|i come back)\b/i,
  r: ['welcome back o 👋','ehen you back','we don miss you'] },
{ p: /\b(i dey go sleep|going to sleep|goodnight all)\b/i,
  r: ['night o 🌙','sleep well','later o'] },
{ p: /\b(make una no vex|una no vex)\b/i,
  r: ['no vex o','we dey o','ok na'] },
{ p: /\b(how una see am)\b/i,
  r: ['we dey watch o','wetyn you think?','e go be'] },
{ p: /\b(wetin you see)\b/i,
  r: ['nothing o','wetyn happen?','talk am'] },
{ p: /\b(i trust you|trust me)\b/i,
  r: ['🙏','ehen na','I sabi you','👍'] },
{ p: /\b(you sabi pass|you sabi well)\b/i,
  r: ['you sef sabi o','chill','🙏'] },
{ p: /\b(well done|nice work|good job)\b/i,
  r: ['thanks o 🙏','👍','appreciate','ehen na'] },
{ p: /\b(no worry about me|i dey ok)\b/i,
  r: ['ok na','ehen','we dey o','chill'] },

// ============ FINAL BIG CATCH-ALL ============
{ p: /.{5,}/,
  r: ['ehn','hmm','ok o','sure','we dey o','chill','na so','I hear you','ehen','alright','talk am','continue','wetin happen?','see talk','oya na','chai','omo'] }

];
module.exports = LIB5;
